// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesAPI.Models;

namespace QuotesAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190331172638_SeedDummyData")]
    partial class SeedDummyData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuotesAPI.Models.QuotesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("QuotesModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Lorem Ipsum1",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Lorem Ipsum2",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Lorem Ipsum3",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Lorem Ipsum4",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Lorem Ipsum5",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Lorem Ipsum6",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Lorem Ipsum7",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Lorem Ipsum8",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Lorem Ipsum9",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Lorem Ipsum10",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Lorem Ipsum11",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Lorem Ipsum12",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Lorem Ipsum13",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Lorem Ipsum14",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Lorem Ipsum15",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Lorem Ipsum16",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Lorem Ipsum17",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Lorem Ipsum18",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Lorem Ipsum19",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Lorem Ipsum20",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.20"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Lorem Ipsum21",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.21"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Lorem Ipsum22",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.22"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Lorem Ipsum23",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.23"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Lorem Ipsum24",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.24"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Lorem Ipsum25",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.25"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Lorem Ipsum26",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.26"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Lorem Ipsum27",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.27"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Lorem Ipsum28",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.28"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Lorem Ipsum29",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.29"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Lorem Ipsum30",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.30"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Lorem Ipsum31",
                            Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse consectetur.31"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
